[application]
out_dir = "dist"

[web.app]
base_path = "algtars"

# HTML title tag content
title = "algtars"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []


